version: "3.9"

services:
  web:
    build: .
    container_name: IndicatorAPIWeb
    restart: on-failure
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    command: bash start.sh
    ports:
      - "8090:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: IndicatorAPIDb
    image: mysql:8
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    build: ./nginx
    container_name: IndicatorAPINginx
    restart: on-failure
    ports:
      - "8091:80"
    volumes:
      - ./static:/static
      - ./media:/media
    depends_on:
      - web

volumes:
  mysql_data: {}